### ISSUE TITLE
Implementation Guide

### ISSUE THREAD

**Issue by cmjchrisjones** [kspearrin/Otp.NET#1]
Hi @kspearrin, I'm really interested in using this library in my solution however I'm not sure where to start or add the `var topt = new Totp(secretKey);`
line, should this go in Startup.cs or somewhere else?

Is there a quick start quide or any thing you can share or direct me to please?

**Comment by kspearrin** [comment]
@cmjchrisjones `var topt = new Totp(secretKey)` just instantiates it for wherever you need to use it. Guide can be found here: https://github.com/kspearrin/Otp.NET/blob/master/README.md
