### ISSUE TITLE
What level of testing coverage is there for Otp.NET?

### ISSUE THREAD

**Issue by madelson** [kspearrin/Otp.NET#18]
Thanks for creating this library! I especially appreciate the effort you put into the documentation.

I am looking to leverage this in an application and one question I have is how heavily-tested this is. On perusal of the source code I wasn't able to find any unit tests, but perhaps they live elsewhere?

**Comment by kspearrin** [comment]
None. This is just a port of https://bitbucket.org/devinmartin/otp-sharp/src , and tests were not brought over.

Happy to accept a PR.

**Comment by mtausig** [comment]
Fixed by #22
