### ISSUE TITLE
What is timeStepMatched?

### ISSUE THREAD

**Issue by arisliang** [kspearrin/Otp.NET#19]
Is there any documentation or example that shows what `timeStepMatched` is, and how it's used?

**Comment by kspearrin** [comment]
Only what is documented in code. See:

https://github.com/kspearrin/Otp.NET/blob/5e8b6db84f385b2910450c141ccec13e15b9201d/src/Otp.NET/Totp.cs#L130

https://github.com/kspearrin/Otp.NET/blob/5e8b6db84f385b2910450c141ccec13e15b9201d/src/Otp.NET/Otp.cs#L102

>  <param name="matchedStep">Output parameter that provides the step where the match was found.  If no match was found it will be 0</param>

**Comment by arisliang** [comment]
Thanks for the quick response!

**Comment by BiriukovKYC** [comment]
@kspearrin I read it but didn't understand anything.
