### ISSUE TITLE
[Questions] - VerifyTotp is incorrect?

### ISSUE THREAD

**Issue by tuongntk** [kspearrin/Otp.NET#20]
Tks for your libs so much

  - I'm using "ComputeTotp" method to generate Otp token with step 30s (expired otp). However I'm check "VerifyTotp" method to verify gererated otp token is valid or not but after 30 seconds the generated otp token is still valid and nearly 1 minute expired after that.
So I'd like to ask you is it correct ? and how to config expired time exactly.    

Tks and have a nice day

**Comment by kspearrin** [comment]
Is your system time correct on both devices?

**Comment by tuongntk** [comment]
Sorry for misunderstanding.
I'll close it right now.
Tks so much
