### ISSUE TITLE
I need my code's validity must be 15 seconds

### ISSUE THREAD

**Issue by reponemec** [kspearrin/Otp.NET#23]
var step = 15; //Code must be valid for 15 seconds.
var secretKey = Base32Encoding.ToBytes("test");            
var totp = new Totp(secretKey, step);
var totpCode = totp.ComputeTotp(); //Let's say this line is running at 08:54:**10** (hh:mm:ss) o'clock.
var verified = totp.VerifyTotp(totpCode, out long timeWindowUsed); //Let's say this line is running at 08:54:**20** (hh:mm:ss): It returns FALSE probably because another step window is reached!

Unfortunately, verified variable is false, so the totpCode is no longer valid 5 seconds before my required expiration (08:54:**25**).

**Comment by mtausig** [comment]
You misunderstood the algorithm. *Step=15* doesn't mean that the code is valid for 15 seconds after you computed it, but for 15 seconds after the beginning of the time window. The computation time may fall anywhere within that timeframe. That's why servers usually accept codes from the previous frame.

**Comment by reponemec** [comment]
> You misunderstood the algorithm. _Step=15_ doesn't mean that the code is valid for 15 seconds after you computed it, but for 15 seconds after the beginning of the time window. The computation time may fall anywhere within that timeframe. That's why servers usually accept codes from the previous frame.



> You misunderstood the algorithm. _Step=15_ doesn't mean that the code is valid for 15 seconds after you computed it, but for 15 seconds after the beginning of the time window. The computation time may fall anywhere within that timeframe. That's why servers usually accept codes from the previous frame.

**Comment by reponemec** [comment]
Thanks for confirming.
