### ISSUE TITLE
How to use Verification in a Web Application and persistent data?

### ISSUE THREAD

**Issue by biapar** [kspearrin/Otp.NET#27]
How to use Verification in a Web Application and persistent data?

**Comment by kspearrin** [comment]
Examples are included in the readme.

**Comment by neil-enjoy** [comment]
Hi.
Your documentation is rather sparse on usage detail.
In particular, it could do with an example of the class you say to create, how it is called and with what parameters and what the return type is.
Thanks.

**Comment by guilhermearv** [comment]
Hi @biapar , I created a web example for learning https://github.com/guilhermearv/OtpNetWebApp2

I hope help you.
