### ISSUE TITLE
Microsoft Authenticator problem

### ISSUE THREAD

**Issue by npendlington** [kspearrin/Otp.NET#28]
Or possibly just a lack of understanding.

I generate a key using a human-readable format as a temporary thing when testing like so:
````
Encoding.ASCII.GetBytes("hello")
````
But the TOTPs that are generated with ````ComputeTotp()```` do not match the value that the Android Microsoft Authenticator app is showing with the same secret entered manually. The phone and PC clocks are within a few ms of each other, so it's not a skewing issue as far as I can tell.

I even tried using the Base32Encoded version of the secret as a key

The Authenticator app claims to be compatible with the RFC, so I can't think what other variable I can change. I'm fairly certain that it uses the SHA1 hashing algorithm (and I did try all of the SHA2 variants just to be sure, and none of these worked either).

**Comment by Tashaa78** [comment]
@npendlington , how did you connect your app to Microsoft Authenticator

**Comment by npendlington** [comment]
Fairly straightforward, but I suspect this is where I'm going wrong:

1. Add account > Other account (Google, Facebook, etc)
2. Click on "Enter code manually"
3. Account name: "Test", Secret Key: "hello" (but I also tried the base-32 encoded "NBSWY3DP")

**Comment by Tashaa78** [comment]
Thanks, thought it was something complicated. Do you by any means know how i can send a notification to a person's phone requesting approval like in the image below?

![authenticator](https://www.digitalcitizen.life/sites/default/files/gdrive/android_microsoft_approve/android_microsoft_approve_10.png "")

**Comment by npendlington** [comment]
@Tashaa78 I don't I'm afraid. I expect it is an extension specific to Microsoft's SSO though. It is something I want to get working as it happens, but I need to get a standard TOTP working to make the solution compatible with Google Authenticator.

**Comment by npendlington** [comment]
Ok. I've resolved my issue. The secret key that is manually typed in must be the BASE32 encoded generated secret. Presumably in my testing I got a false negative by typing the key in wrong. 

As soon as I produced a standard QR code to allow me to not make the human error of typing it in, it worked.
