### ISSUE TITLE
incompatible version

### ISSUE THREAD

**Issue by findli** [kspearrin/Otp.NET#32]
[Notification][Install] Install failed (project: GoogleAuth, package: Otp.NET v1.2.2)

Could not install package 'Otp.NET 1.2.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by kspearrin** [comment]
This package is not compatible with .NET Framework 4.0
