### ISSUE TITLE
Strong Name Key

### ISSUE THREAD

**Issue by AlexanderJ-ULabs** [kspearrin/Otp.NET#4]
Hi kspearrin! Your OTP solution is excellent, but I do have a small request. Would you sign it with a strong name key so that it will work natively with other strongly named assemblies? For now I can re-compile the source with a key on my own, but I think this would be a nice feature for your other users via NuGet.

**Comment by kspearrin** [comment]
I added version 1.1.0 to nuget which should be signed. Please let me know if that works.

**Comment by AlexanderJ-ULabs** [comment]
Thanks a ton for adding in the new version. I meant to get back to you sooner about this, but I'm having trouble using the 1.1.0 version. I'm around 99% positive that it's a fault on my end because I was using a clone of your source with my own name key.

As soon as I have it sorted out then I will report back to let you know everything is working.

**Comment by AlexanderJ-ULabs** [comment]
Hi, back with some more information.

I have a solution with a core project which is currently being developed for .NET Standard 2.0. All of the dependencies and projects are loaded at runtime when requested. So the process goes as follows:

Core project starts => Request to load OTP project => Request to load Otp.Net

If I download your source and sign it with my own throwaway key, then I can reference the .NET Standard 1.3 dll file without any issues. OTP works beautifully well.

The problem comes in when I try to reference it from NuGet instead. That's when I get the exception in my previous post. I wasn't able to sort out why that was happening, so I reverted back to re-compiling your source for now.

At some point I'll be able to get back to diagnosing the NuGet problem, but in the mean time I just needed some working OTP for development/testing purposes.

**Comment by kspearrin** [comment]
Not sure. I am using it in my .NET Core 2.0 project just fine.

**Comment by AlexanderJ-ULabs** [comment]
it must be that I'm running it under Framework 4.6.1 because if I load the net45/OTP.Net.DLL file then I get the same problem as the NuGet error.

Clearly this is an issue with my hacky setup and not your code. :)
