### ISSUE TITLE
When mode = OtpHashMode.Sha512 Microsoft Authenticator gen wrong code

### ISSUE THREAD

**Issue by romulocrj** [kspearrin/Otp.NET#54]
I'm not sure if it's an error in this lib or the app. But when the mode is set to OtpHashMode.Sha512, the codes generated by Microsoft Authenticator do not work, while those from Google Authenticator work.
Putting it in Sha1 both work.

**Comment by kspearrin** [comment]
My guess is Microsoft Authenticator doesn't support Sha512 and is probably generating Sha1 codes.

**Comment by romulocrj** [comment]
Exactly. 
I found this thread: 
https://answers.microsoft.com/en-us/msoffice/forum/all/authenticator-app-not-working-with-sha-256-and-sha/f0023746-2d4b-499e-aee5- 2463d96a8144
