### ISSUE TITLE
This line is kind of strange

### ISSUE THREAD

**Issue by marianpascalau** [kspearrin/Otp.NET#55]
https://github.com/kspearrin/Otp.NET/blob/14a0a1cc605a333ba9e2d16e60898ba4ce6bf394/src/Otp.NET/Otp.cs#L108

Hallo,
I just want to tell you that this line is strange (Otp.cs, 108). First, because it does not work (and this is good) and second, the module operation is implemented later anyway, when the Otp string is truncated with the size specified in "otp-size" setting.

The modulo 1000000 there which should in principle keep only the last 6 digits must be something from older times when the OTP was probably hardcoded to 6 digits long. But due to the fact that the compiler is running "last byte modulo 100000" the result is always the "last byte" because an "unsigned byte" is maximal 255 big. And this is OK, because otherwise we would have had a problem if we would expected OTPs with more than 6 digits.

Regards

**Comment by kspearrin** [comment]
Resolved with https://github.com/kspearrin/Otp.NET/pull/31
