### ISSUE TITLE
Generated codes do not match Google Authenticator results

### ISSUE THREAD

**Issue by derekantrican** [kspearrin/Otp.NET#8]
I am using this code:

    string secret = "KREQPD7NXSGO3T3B";
    while (true)
    {
        byte[] secretBytes = new Base32Encoder().Decode(secret);
        OtpNet.Totp totp = new OtpNet.Totp(secretBytes);
        string twoFactorCode = totp.ComputeTotp();
    
        Console.WriteLine("Two factor code: " + twoFactorCode);
    
        System.Threading.Thread.Sleep(2000);
    }

Now if you take that same string (for `secret`) and put it in to Google Authenticator manually, you will notice that this code generates different keys. On the otherhand, if I use a different value for secret (eg "uhj34qsyuwftzji4qq6k3c3wnstdb57m") then both the values generated by OtpNet and Google Authenticator will match.

What am I doing wrong?

**Comment by kspearrin** [comment]
Is KREQPD7NXSGO3T3B a valid base32 value for a totp key?

**Comment by derekantrican** [comment]
@kspearrin I'm not sure. I was following the instructions in this article: https://dev.to/j_sakamoto/selenium-testing---how-to-sign-in-to-two-factor-authentication-2joi

Is there a way to verify that?

**Comment by derekantrican** [comment]
@kspearrin the two factor uri that I got from the QR code is like this (I have since changed my two factor code on Facebook): `otpauth://totp/derekantrican?secret=KREQPD7NXSGO3T3B&digits=6&issuer=Facebook`

**Comment by shyboylpf** [comment]
@kspearrin Is there any way to generate otpauth that will let OtpNet and Google Authenticator match?
I am using this code:
`string OtpSecretKey = "KREQPD7NXSGO3T3B";`
`var secretKey = System.Text.Encoding.Unicode.GetBytes(OtpSecretKey);`
`var totp = new Totp(secretKey);`
`var totpCode = totp.ComputeTotp(DateTime.UtcNow);`

What am I doing wrong with the GetBytes or others?
Thanks.

**Comment by shyboylpf** [comment]
I just got it.
The way to get bytes[] is wrong.
I need to use 
`var secretKey = Base32Encoding.ToBytes(OtpSecretKey);`
Then OtpNet and Google Authenticator will match.

**Comment by derekantrican** [comment]
@shyboylpf Great, thanks! That was it!

**Comment by shyboylpf** [comment]
@derekantrican Great
